@extends('layouts.app')
@section('title',$setup->name) @section('section','Admissions · Admin Setups')
@section('content')
<div class="page-head"><div><a href="{{ route('admissions.setups.index') }}">← All setups</a><div class="eyebrow">{{ $setup->category }}</div><h1 class="heading">{{ $setup->name }}</h1><p class="sub">Consumed by {{ $setup->consumer }}. {{ $setup->missing_behaviour }}</p></div></div>
<div class="report-layout"><section class="panel"><div class="panel-head"><h2>Create draft version</h2></div><form method="post" action="{{ route('admissions.setups.store',$setup) }}" style="display:grid;gap:12px">@csrf<label><strong>Configuration JSON</strong><textarea name="configuration" rows="16" style="width:100%;font-family:monospace" required>{
  "enabled": true
}</textarea></label><label><strong>Change reason</strong><input name="change_reason" required maxlength="500" style="width:100%"></label><button class="btn">Create draft</button></form></section>
<section class="panel"><div class="panel-head"><h2>Version history</h2></div>@forelse($setup->versions as $version)<article style="padding:14px 0;border-bottom:1px solid var(--line)"><div style="display:flex;justify-content:space-between;gap:12px"><strong>Version {{ $version->version }}</strong><span class="badge">{{ $version->status }}</span></div><small>Checksum {{ substr($version->checksum,0,12) }}… · {{ $version->usages_count }} historical uses</small><pre style="white-space:pre-wrap;background:#f5f8f9;padding:10px;border-radius:8px">{{ json_encode($version->configuration, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre>@if($version->status==='DRAFT')<form method="post" action="{{ route('admissions.setups.publish',$version) }}" style="display:flex;gap:8px;align-items:end">@csrf<label>Effective from<input type="date" name="effective_from" required></label><label>Effective to<input type="date" name="effective_to"></label><button class="btn">Validate & publish</button></form>@elseif($version->status==='ACTIVE')<form method="post" action="{{ route('admissions.setups.status',$version) }}">@csrf @method('patch')<input type="hidden" name="status" value="INACTIVE"><button class="btn btn-secondary">Deactivate</button></form>@endif</article>@empty<div class="empty">No versions yet. Create the first draft configuration.</div>@endforelse</section></div>
@endsection
