'use client';

import React, { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { api, ApiError, type IamRoleSummary, type IamUserSummary } from '@mema/api-client';
import { Alert, AlertDescription, AlertTitle, Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@mema/ui';
import { Plus, RefreshCw, ShieldCheck, UserCog, Users } from 'lucide-react';

const fieldClass = 'h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-slate-900 focus:border-transparent focus:outline-none focus:ring-2 focus:ring-mema-teal-700';
const labelClass = 'space-y-1 text-sm font-medium text-slate-700';
const messageFrom = (reason: unknown) => reason instanceof ApiError ? reason.message : 'The IAM operation could not be completed.';

export default function AdminSecurityPage() {
  const [users, setUsers] = useState<IamUserSummary[]>([]); const [roles, setRoles] = useState<IamRoleSummary[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null); const [showProvisioning, setShowProvisioning] = useState(false);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [userResponse, roleResponse] = await Promise.all([api.getIamUsers(), api.getIamRoles()]); setUsers(userResponse.data); setRoles(roleResponse.data); } catch (reason) { setError(messageFrom(reason)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const selected = useMemo(() => users.find((user) => user.id === selectedId) ?? null, [users, selectedId]);
  async function perform(action: () => Promise<void>, success: string) { setSaving(true); setError(null); setNotice(null); try { await action(); setNotice(success); await load(); } catch (reason) { setError(messageFrom(reason)); } finally { setSaving(false); } }
  async function provision(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); await perform(async () => { await api.createIamUser({ given_name: String(form.get('given_name')), family_name: String(form.get('family_name')), email: String(form.get('email')), username: String(form.get('username')), identity_type: String(form.get('identity_type')) as 'APPLICANT' | 'STUDENT' | 'EMPLOYEE' | 'ALUMNI', identifier: String(form.get('identifier')), password: String(form.get('password')) }); formElement.reset(); setShowProvisioning(false); }, 'User provisioned in PENDING state.'); }
  async function updateStatus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); await perform(() => api.updateIamUserStatus(selected.id, String(form.get('status')) as IamUserSummary['status'], String(form.get('reason'))), 'Account status updated and affected sessions revoked.'); }
  async function assignRole(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); const scopeId = String(form.get('scope_id') ?? ''); const startsAt = String(form.get('starts_at') ?? ''); const endsAt = String(form.get('ends_at') ?? ''); await perform(() => api.assignIamRole(selected.id, { role_id: String(form.get('role_id')), scope_type: String(form.get('scope_type')) as IamRoleSummary['default_scope_type'], ...(scopeId ? { scope_id: scopeId } : {}), ...(startsAt ? { starts_at: startsAt } : {}), ...(endsAt ? { ends_at: endsAt } : {}), reason: String(form.get('reason')) }), 'Scoped role assigned; the user must sign in again.'); }
  async function resetMfa(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); await perform(() => api.resetIamUserMfa(selected.id, String(form.get('reason'))), 'MFA reset completed and all user sessions revoked.'); }

  return <div className="space-y-8">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-heading text-2xl font-bold text-slate-900">Identity & Access Management</h2><p className="mt-1 text-sm text-slate-500">Provision accounts, control lifecycle state, recover MFA, and grant time-bound scoped roles.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void load()} isLoading={loading}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button><Button onClick={() => setShowProvisioning((value) => !value)}><Plus className="mr-2 h-4 w-4" />Provision user</Button></div></div>
    {error && <Alert variant="destructive"><AlertTitle>IAM operation failed</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{notice && <Alert variant="success"><AlertTitle>Operation completed</AlertTitle><AlertDescription>{notice}</AlertDescription></Alert>}
    {showProvisioning && <Card><CardHeader><CardTitle>Provision institutional account</CardTitle><CardDescription>A person, institutional identity, and pending login account are created atomically.</CardDescription></CardHeader><CardContent><form onSubmit={provision} className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className={labelClass}>Given name<Input name="given_name" required /></label><label className={labelClass}>Family name<Input name="family_name" required /></label><label className={labelClass}>Institutional email<Input name="email" type="email" required /></label><label className={labelClass}>Username<Input name="username" required /></label><label className={labelClass}>Identity type<select name="identity_type" className={fieldClass} defaultValue="EMPLOYEE"><option>EMPLOYEE</option><option>STUDENT</option><option>APPLICANT</option><option>ALUMNI</option></select></label><label className={labelClass}>Institutional identifier<Input name="identifier" required /></label><label className={labelClass}>Temporary password<Input name="password" type="password" required minLength={12} /></label><div className="flex items-end"><Button type="submit" isLoading={saving}>Create pending account</Button></div></form></CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="flex items-center gap-3 p-5"><Users className="h-7 w-7 text-mema-teal-700" /><div><div className="text-2xl font-bold">{users.length}</div><div className="text-xs text-slate-500">Visible accounts</div></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-5"><ShieldCheck className="h-7 w-7 text-mema-teal-700" /><div><div className="text-2xl font-bold">{roles.length}</div><div className="text-xs text-slate-500">Enterprise roles</div></div></CardContent></Card><Card><CardContent className="p-5"><div className="text-2xl font-bold">{users.filter((user) => user.mfa_enabled).length}</div><div className="text-xs text-slate-500">MFA-enrolled accounts</div></CardContent></Card></div>
    <Card><CardHeader><CardTitle>User account governance</CardTitle><CardDescription>Select an account to perform controlled administrative actions.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead>Status</TableHead><TableHead>MFA</TableHead><TableHead>Scoped roles</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{users.map((user) => <TableRow key={user.id}><TableCell><div className="font-medium text-slate-900">{user.name || user.username || user.email}</div><div className="text-xs text-slate-500">{user.email}</div></TableCell><TableCell><Badge variant={user.is_active ? 'success' : 'warning'}>{user.status}</Badge></TableCell><TableCell><Badge variant={user.mfa_enabled ? 'success' : 'outline'}>{user.mfa_enabled ? 'Enabled' : 'Not enrolled'}</Badge></TableCell><TableCell><div className="flex flex-wrap gap-1">{user.roles.map((role) => <Badge key={role.id} variant="outline">{role.code} · {role.scope_type}</Badge>)}</div></TableCell><TableCell><Button size="sm" variant={selectedId === user.id ? 'default' : 'outline'} onClick={() => setSelectedId(user.id)}><UserCog className="mr-2 h-4 w-4" />Manage</Button></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
    {selected && <Card><CardHeader><CardTitle>Manage {selected.name || selected.email}</CardTitle><CardDescription>Every change requires a reason and is written to the audit trail.</CardDescription></CardHeader><CardContent className="grid gap-6 xl:grid-cols-3"><form onSubmit={updateStatus} className="space-y-3 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">Account status</h3><label className={labelClass}>New status<select name="status" aria-label="New status" className={fieldClass} defaultValue={selected.status}><option>PENDING</option><option>ACTIVE</option><option>LOCKED</option><option>SUSPENDED</option><option>DEACTIVATED</option></select></label><label className={labelClass}>Reason<Input name="reason" required minLength={8} /></label><Button type="submit" isLoading={saving}>Update status</Button></form><form onSubmit={assignRole} className="space-y-3 rounded-xl border border-slate-200 p-4"><h3 className="font-semibold">Scoped role assignment</h3><label className={labelClass}>Role<select name="role_id" aria-label="Role" className={fieldClass} required>{roles.map((role) => <option key={role.id} value={role.id}>{role.name} ({role.code})</option>)}</select></label><label className={labelClass}>Scope<select name="scope_type" aria-label="Scope" className={fieldClass} defaultValue="institution"><option value="institution">Institution</option><option value="campus">Campus</option><option value="faculty">Faculty</option><option value="department">Department</option><option value="self">Self</option></select></label><label className={labelClass}>Scope ID (organisational scopes)<Input name="scope_id" /></label><div className="grid grid-cols-2 gap-2"><label className={labelClass}>Starts at<Input name="starts_at" type="datetime-local" /></label><label className={labelClass}>Ends at<Input name="ends_at" type="datetime-local" /></label></div><label className={labelClass}>Grant reason<Input name="reason" required minLength={8} /></label><Button type="submit" isLoading={saving}>Assign role</Button></form><form onSubmit={resetMfa} className="space-y-3 rounded-xl border border-amber-200 bg-amber-50/40 p-4"><h3 className="font-semibold">MFA account recovery</h3><p className="text-sm text-slate-600">Use only after helpdesk identity verification. This clears factors and revokes every session.</p><label className={labelClass}>Verification and recovery reason<Input name="reason" required minLength={8} /></label><Button type="submit" variant="destructive" isLoading={saving}>Reset MFA and sessions</Button></form></CardContent></Card>}
    <Card><CardHeader><CardTitle>Role directory</CardTitle><CardDescription>55 protected roles normalized into 11 enterprise families.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Role</TableHead><TableHead>Family</TableHead><TableHead>MFA</TableHead><TableHead className="text-right">Assignments</TableHead><TableHead className="text-right">Permissions</TableHead></TableRow></TableHeader><TableBody>{roles.map((role) => <TableRow key={role.id}><TableCell><div className="font-medium">{role.name}</div><div className="font-mono text-xs text-mema-teal-800">{role.code}</div></TableCell><TableCell>{role.family}</TableCell><TableCell><Badge variant={role.is_mfa_mandatory ? 'warning' : 'outline'}>{role.is_mfa_mandatory ? 'Required' : 'Optional'}</Badge></TableCell><TableCell className="text-right">{role.assignments_count}</TableCell><TableCell className="text-right">{role.permissions_count}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
  </div>;
}
