<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\View\View;

final class StudentTransferController extends Controller
{
    public function exemptions(Request $request): View
    {
        $status = $request->query('status');
        $search = $request->query('search');

        $stats = [
            'totalRequests' => 1683,
            'pendingApprovals' => 321,
            'unassignedPending' => 158,
            'approvedExemptions' => 1147,
            'rejectedRequests' => 148,
            'totalRate' => '+100%',
            'pendingRate' => '+19.07%',
            'approvedRate' => '+68.15%',
            'rejectedRate' => '+8.79%',
        ];

        $allEntries = [
            [
                'id' => 1,
                'name' => 'DANIEL KIBET',
                'admission_number' => 'BE02/33013/2025',
                'course_code' => 'ECO 101',
                'course_name' => 'Introduction to Microeconomics',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'INSTRUCTOR SENTBACK',
                'status_type' => 'sentback',
            ],
            [
                'id' => 2,
                'name' => 'DELANY MUKARIA',
                'admission_number' => 'BE02/35640/2025',
                'course_code' => 'BEB 103',
                'course_name' => 'Introduction to Management and Business Studies',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 3,
                'name' => 'FIDELIS MARUCHA',
                'admission_number' => 'BE02/50600/2024',
                'course_code' => 'ECO 101',
                'course_name' => 'Introduction to Microeconomics',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'INSTRUCTOR SENTBACK',
                'status_type' => 'sentback',
            ],
            [
                'id' => 4,
                'name' => 'FIDELIS MARUCHA',
                'admission_number' => 'BE02/50600/2024',
                'course_code' => 'ECO 102',
                'course_name' => 'Introduction to Macroeconomics',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'HOD REJECTED',
                'status_type' => 'rejected',
            ],
            [
                'id' => 5,
                'name' => 'HILDAH AYABEI',
                'admission_number' => 'BE02/34324/2025',
                'course_code' => 'ECO 101',
                'course_name' => 'Introduction to Microeconomics',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'INSTRUCTOR SENTBACK',
                'status_type' => 'sentback',
            ],
            [
                'id' => 6,
                'name' => 'IRENE KOECH',
                'admission_number' => 'BE02/33890/2025',
                'course_code' => 'ECO 101',
                'course_name' => 'Introduction to Microeconomics',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'INSTRUCTOR SENTBACK',
                'status_type' => 'sentback',
            ],
            [
                'id' => 7,
                'name' => 'CYNTHIA CHEPKURUI',
                'admission_number' => 'BE02/35112/2025',
                'course_code' => 'BEB 101',
                'course_name' => 'Business Mathematics and Statistics',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'PENDING',
                'status_type' => 'pending',
            ],
            [
                'id' => 8,
                'name' => 'BRIAN OMONDI',
                'admission_number' => 'CS01/29840/2025',
                'course_code' => 'CSC 102',
                'course_name' => 'Structured Programming with C',
                'programme_code' => 'CS01',
                'programme_name' => 'Bachelor of Science in Computer Science',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 9,
                'name' => 'MERCY WAMBUI',
                'admission_number' => 'ED01/31902/2024',
                'course_code' => 'EDF 101',
                'course_name' => 'History and Foundations of Education',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'RECOMMENDED',
                'status_type' => 'recommended',
            ],
            [
                'id' => 10,
                'name' => 'KEVIN OTIENO',
                'admission_number' => 'BE02/32450/2025',
                'course_code' => 'BEB 105',
                'course_name' => 'Financial Accounting I',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'HOD SENDBACK',
                'status_type' => 'sentback',
            ],
            [
                'id' => 11,
                'name' => 'GLADYS CHERONO',
                'admission_number' => 'CS01/30012/2025',
                'course_code' => 'MAT 102',
                'course_name' => 'Discrete Mathematics',
                'programme_code' => 'CS01',
                'programme_name' => 'Bachelor of Science in Computer Science',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 12,
                'name' => 'SAMUEL WAWERU',
                'admission_number' => 'ED01/32890/2025',
                'course_code' => 'PSY 101',
                'course_name' => 'Introduction to Educational Psychology',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'STUDENT SENDBACK',
                'status_type' => 'sentback',
            ],
            [
                'id' => 13,
                'name' => 'SHARON JEPKEMOI',
                'admission_number' => 'BE02/34812/2025',
                'course_code' => 'BEB 107',
                'course_name' => 'Principles of Marketing',
                'programme_code' => 'BE02',
                'programme_name' => 'Bachelor of Entrepreneurship and Business',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 14,
                'name' => 'VICTOR KIPKEMBOI',
                'admission_number' => 'CS01/31200/2025',
                'course_code' => 'CSC 104',
                'course_name' => 'Database Systems Design',
                'programme_code' => 'CS01',
                'programme_name' => 'Bachelor of Science in Computer Science',
                'status' => 'PENDING',
                'status_type' => 'pending',
            ],
            [
                'id' => 15,
                'name' => 'ESTHER NYAMBURA',
                'admission_number' => 'ED01/33100/2025',
                'course_code' => 'EDC 101',
                'course_name' => 'Curriculum Development',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 16,
                'name' => 'ABDULLAHI GUHAT',
                'admission_number' => 'ED01/33239/2025',
                'course_code' => 'BEB 109',
                'course_name' => 'Critical Thinking',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 17,
                'name' => 'ABDULLAHI GUHAT',
                'admission_number' => 'ED01/33239/2025',
                'course_code' => 'SST 201',
                'course_name' => 'Probability and Statistics',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 18,
                'name' => 'BETTY MUNYOKI',
                'admission_number' => 'ED01/34411/2025',
                'course_code' => 'MAT 103',
                'course_name' => 'Calculus I',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 19,
                'name' => 'BETTY MUNYOKI',
                'admission_number' => 'ED01/34411/2025',
                'course_code' => 'CSC 101',
                'course_name' => 'Introduction to Computing Systems',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
            [
                'id' => 20,
                'name' => 'BETTY MUNYOKI',
                'admission_number' => 'ED01/34411/2025',
                'course_code' => 'MAT 101',
                'course_name' => 'Foundations of Mathematics',
                'programme_code' => 'ED01',
                'programme_name' => 'Bachelor of Technology Education',
                'status' => 'APPROVED',
                'status_type' => 'approved',
            ],
        ];

        return view('transfers.exemptions', compact('stats', 'allEntries', 'status', 'search'));
    }

    public function datesSetup(): View
    {
        $dates = [
            [
                'id' => 1,
                'type' => 'Credit Transfer',
                'academic_year' => '2023-2024',
                'notification_date' => '19-02-2025',
                'start_date' => '07-09-2026',
                'end_date' => '27-05-2025',
            ],
            [
                'id' => 2,
                'type' => 'Credit Transfer',
                'academic_year' => '2026-2027',
                'notification_date' => '09-07-2026',
                'start_date' => '09-07-2026',
                'end_date' => '30-11-2026',
            ],
            [
                'id' => 3,
                'type' => 'Credit Transfer',
                'academic_year' => '2025-2026',
                'notification_date' => '11-07-2025',
                'start_date' => '11-07-2025',
                'end_date' => '06-08-2026',
            ],
            [
                'id' => 4,
                'type' => 'Credit Transfer',
                'academic_year' => '2024-2025',
                'notification_date' => '15-10-2024',
                'start_date' => '15-10-2024',
                'end_date' => '31-05-2025',
            ],
            [
                'id' => 5,
                'type' => 'Inter/Intra SchoolTransfer',
                'academic_year' => '2023-2024',
                'notification_date' => '05-04-2024',
                'start_date' => '05-07-2024',
                'end_date' => '05-11-2024',
            ],
            [
                'id' => 6,
                'type' => 'Inter/Intra SchoolTransfer',
                'academic_year' => '2026-2027',
                'notification_date' => '09-07-2026',
                'start_date' => '07-09-2026',
                'end_date' => '07-09-2026',
            ],
            [
                'id' => 7,
                'type' => 'Inter/Intra SchoolTransfer',
                'academic_year' => '2025-2026',
                'notification_date' => '11-07-2025',
                'start_date' => '11-07-2025',
                'end_date' => '31-07-2026',
            ],
            [
                'id' => 8,
                'type' => 'Inter/Intra SchoolTransfer',
                'academic_year' => '2024-2025',
                'notification_date' => '04-09-2024',
                'start_date' => '04-09-2024',
                'end_date' => '31-08-2025',
            ],
        ];

        return view('transfers.dates-setup', compact('dates'));
    }

    public function interIntra(Request $request): View
    {
        $status = $request->query('status');
        $search = $request->query('search');

        $transfers = [
            [
                'id' => 1,
                'name' => 'ABDIHAKIM OMAR',
                'email' => 'ST63801212024@students.mema.ac.ke',
                'reg_no' => 'ST63/80121/2024',
                'type' => 'Intra',
                'current_programme' => 'ST61 - Master of Data Science',
                'transfer_programme' => 'ST63 - Master of Science in Cybersecurity and Digital Forensics',
                'reason' => 'Change of Preference',
                'status' => 'Pending',
            ],
            [
                'id' => 2,
                'name' => 'ABDINASIR AHMED SHEIKH ABDI',
                'email' => 'ST0201232024@students.mema.ac.ke',
                'reg_no' => 'ST02/0123/2024',
                'type' => 'Intra',
                'current_programme' => 'ST02 - Bachelor of Science in Cybersecurity and Digital Forensics',
                'transfer_programme' => 'ST04 - Bachelor of Science in Computer Science',
                'reason' => 'Change of Preference',
                'status' => 'Pending',
            ],
            [
                'id' => 3,
                'name' => 'ABDINASIR AHMED SHEIKH ABDI',
                'email' => 'ST0201232024@students.mema.ac.ke',
                'reg_no' => 'ST02/0123/2024',
                'type' => 'Intra',
                'current_programme' => 'ST04 - Bachelor of Science in Computer Science',
                'transfer_programme' => 'ST02 - Bachelor of Science in Cybersecurity and Digital Forensics',
                'reason' => 'Applied for wrong Course',
                'status' => 'Approved',
            ],
            [
                'id' => 4,
                'name' => 'ABEL WANJALA',
                'email' => 'ED63599572025@students.mema.ac.ke',
                'reg_no' => 'ED63/59957/2025',
                'type' => 'Intra',
                'current_programme' => 'ED61 - Master in Learning Design and Technology',
                'transfer_programme' => 'ED63 - Master of Education in Educational Leadership and Policy',
                'reason' => 'Change of Preference',
                'status' => 'Rejected',
            ],
            [
                'id' => 5,
                'name' => 'ABRAHAM KATAM',
                'email' => 'ED62571302025@students.mema.ac.ke',
                'reg_no' => 'ED62/57130/2025',
                'type' => 'Intra',
                'current_programme' => 'ED63 - Master of Education in Educational Leadership and Policy',
                'transfer_programme' => 'ED62 - Master of Education in Technology Education',
                'reason' => '4',
                'status' => 'Approved',
            ],
            [
                'id' => 6,
                'name' => 'ADAM Namunyu',
                'email' => 'ED61580422025@students.mema.ac.ke',
                'reg_no' => 'ED61/58042/2025',
                'type' => 'Intra',
                'current_programme' => 'ED62 - Master of Education in Technology Education',
                'transfer_programme' => 'ED61 - Master in Learning Design and Technology',
                'reason' => 'Applied for wrong Course',
                'status' => 'Approved',
            ],
            [
                'id' => 7,
                'name' => 'ADAN ABDI',
                'email' => 'BE03356702025@students.mema.ac.ke',
                'reg_no' => 'BE03/35670/2025',
                'type' => 'Intra',
                'current_programme' => 'BE04 - Bachelor of Commerce',
                'transfer_programme' => 'BE03 - Bachelor of Economics and Data Science',
                'reason' => 'Change of Preference',
                'status' => 'Approved',
            ],
            [
                'id' => 8,
                'name' => 'ADAN SOMO',
                'email' => 'BE61571332025@students.mema.ac.ke',
                'reg_no' => 'BE61/57133/2025',
                'type' => 'Inter',
                'current_programme' => 'ST61 - Master of Data Science',
                'transfer_programme' => 'BE61 - Master of Business Administration',
                'reason' => 'Change of Preference',
                'status' => 'Approved',
            ],
            [
                'id' => 9,
                'name' => 'AGATHA MAINGI',
                'email' => 'ED61569192025@students.mema.ac.ke',
                'reg_no' => 'ED61/56919/2025',
                'type' => 'Intra',
                'current_programme' => 'ED63 - Master of Education in Educational Leadership and Policy',
                'transfer_programme' => 'ED61 - Master in Learning Design and Technology',
                'reason' => 'Change of Preference',
                'status' => 'Approved',
            ],
            [
                'id' => 10,
                'name' => 'Agnes Wanambisi',
                'email' => 'ST01342022025@students.mema.ac.ke',
                'reg_no' => 'ST01/34202/2025',
                'type' => 'Intra',
                'current_programme' => 'ST02 - Bachelor of Science in Cybersecurity and Digital Forensics',
                'transfer_programme' => 'ST01 - Bachelor of Data Science',
                'reason' => '4',
                'status' => 'Pending',
            ],
        ];

        return view('transfers.inter-intra', compact('transfers', 'status', 'search'));
    }

    public function creditTransfers(Request $request): View
    {
        $status = $request->query('status');
        $search = $request->query('search');

        $stats = [
            'totalRequests' => 274,
            'pendingApprovals' => 166,
            'unassignedPending' => 100,
            'approvedTransfers' => 75,
            'rejectedRequests' => 17,
            'totalRate' => '+100%',
            'pendingRate' => '+60.58%',
            'approvedRate' => '+27.37%',
            'rejectedRate' => '+6.2%',
        ];

        $creditEntries = [
            [
                'id' => 1,
                'name' => 'JARED ORWA',
                'admission_number' => 'BE01/56068/2023',
                'course_code' => 'BEB 107',
                'course_name' => 'Entrepreneurial Environment',
                'programme_code' => 'BE01',
                'programme_name' => 'Bachelor of Economics and Statistics',
                'status' => 'Instructor sentback',
                'status_type' => 'sentback',
            ],
            [
                'id' => 2,
                'name' => 'JARED ORWA',
                'admission_number' => 'BE01/56068/2023',
                'course_code' => 'CSC 101',
                'course_name' => 'Introduction to Computing Systems',
                'programme_code' => 'BE01',
                'programme_name' => 'Bachelor of Economics and Statistics',
                'status' => 'Instructor sentback',
                'status_type' => 'sentback',
            ],
            [
                'id' => 3,
                'name' => 'JARED ORWA',
                'admission_number' => 'BE01/56068/2023',
                'course_code' => 'SST 111',
                'course_name' => 'Basic Statistics with R',
                'programme_code' => 'BE01',
                'programme_name' => 'Bachelor of Economics and Statistics',
                'status' => 'Instructor sentback',
                'status_type' => 'sentback',
            ],
            [
                'id' => 4,
                'name' => 'JARED ORWA',
                'admission_number' => 'BE01/56068/2023',
                'course_code' => 'ECO 101',
                'course_name' => 'Introduction to Microeconomics',
                'programme_code' => 'BE01',
                'programme_name' => 'Bachelor of Economics and Statistics',
                'status' => 'Instructor sentback',
                'status_type' => 'sentback',
            ],
            [
                'id' => 5,
                'name' => 'JARED ORWA',
                'admission_number' => 'BE01/56068/2023',
                'course_code' => 'MAT 101',
                'course_name' => 'Foundations of Mathematics',
                'programme_code' => 'BE01',
                'programme_name' => 'Bachelor of Economics and Statistics',
                'status' => 'approved',
                'status_type' => 'approved',
            ],
            [
                'id' => 6,
                'name' => 'MICHAEL LIWAN',
                'admission_number' => 'ST01/55027/2023',
                'course_code' => 'MAT 102',
                'course_name' => 'Differential and Integral Calculus',
                'programme_code' => 'ST01',
                'programme_name' => 'Bachelor of Data Science',
                'status' => 'approved',
                'status_type' => 'approved',
            ],
            [
                'id' => 7,
                'name' => 'BEN TITO',
                'admission_number' => 'ST01/56162/2023',
                'course_code' => 'BEB 105',
                'course_name' => 'IT Entrepreneurship',
                'programme_code' => 'ST01',
                'programme_name' => 'Bachelor of Data Science',
                'status' => 'Instructor sentback',
                'status_type' => 'sentback',
            ],
            [
                'id' => 8,
                'name' => 'LINET LYDIA',
                'admission_number' => 'ST01/50451/2024',
                'course_code' => 'CSC 101',
                'course_name' => 'Introduction to Computing Systems',
                'programme_code' => 'ST01',
                'programme_name' => 'Bachelor of Data Science',
                'status' => 'approved',
                'status_type' => 'approved',
            ],
            [
                'id' => 9,
                'name' => 'SABASTIAN NZIOKA',
                'admission_number' => 'BE04/33812/2025',
                'course_code' => 'BCM 101',
                'course_name' => 'Introduction to Business Mathematics',
                'programme_code' => 'BE04',
                'programme_name' => 'Bachelor of Commerce',
                'status' => 'approved',
                'status_type' => 'approved',
            ],
            [
                'id' => 10,
                'name' => 'SABASTIAN NZIOKA',
                'admission_number' => 'BE04/33812/2025',
                'course_code' => 'BCM 103',
                'course_name' => 'Introduction to Financial Accounting',
                'programme_code' => 'BE04',
                'programme_name' => 'Bachelor of Commerce',
                'status' => 'approved',
                'status_type' => 'approved',
            ],
        ];

        return view('transfers.credit-transfers', compact('stats', 'creditEntries', 'status', 'search'));
    }
}
