<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * The canonical person spine.
 *
 * One human being = exactly one row in `student.persons`, for their entire relationship with the
 * institution. An applicant who becomes a student, graduates, is hired as a tutorial fellow and later
 * donates as an alumnus is ONE person row with four role records — never four accounts.
 *
 * Person rows are never hard-deleted. Identities are added and closed, never replaced.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('student.persons', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('institution_id')->constrained('institution.institutions')->cascadeOnDelete();

            $table->string('given_name');
            $table->string('middle_name')->nullable();
            $table->string('family_name');
            $table->date('date_of_birth')->nullable();
            $table->string('gender', 16)->nullable();
            $table->string('nationality', 2)->nullable();

            // Identity documents — the basis for deduplication at every intake point.
            $table->string('national_id', 64)->nullable();
            $table->string('passport_number', 64)->nullable();
            $table->string('birth_certificate_number', 64)->nullable();

            $table->string('primary_email')->nullable();
            $table->string('primary_phone', 32)->nullable();
            $table->jsonb('address')->default('{}');

            $table->timestampsTz();

            $table->index(['institution_id', 'family_name', 'given_name']);
        });

        // A national ID uniquely identifies a person within an institution when present.
        // Partial unique indexes let the many legitimately-null rows coexist.
        DB::statement('CREATE UNIQUE INDEX persons_national_id_unique
            ON student.persons (institution_id, national_id)
            WHERE national_id IS NOT NULL');

        DB::statement('CREATE UNIQUE INDEX persons_passport_unique
            ON student.persons (institution_id, passport_number)
            WHERE passport_number IS NOT NULL');

        // Fuzzy name search for registry staff reconciling duplicates.
        DB::statement('CREATE INDEX persons_name_trgm
            ON student.persons USING gin ((given_name || \' \' || family_name) gin_trgm_ops)');

        // The identities a person holds. A person may hold several at once.
        Schema::create('student.person_identities', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('institution_id')->constrained('institution.institutions')->cascadeOnDelete();
            $table->foreignUuid('person_id')->constrained('student.persons')->cascadeOnDelete();

            // applicant | student | employee | alumnus | affiliate
            $table->string('identity_type', 32);

            // The number the world knows them by in this role: admission number,
            // registration number, staff number. Generated by MOD-00-03 numbering rules.
            $table->string('identifier', 64);

            $table->string('status', 32)->default('active');
            $table->date('started_on');
            $table->date('ended_on')->nullable();
            $table->jsonb('metadata')->default('{}');
            $table->timestampsTz();

            $table->unique(['institution_id', 'identity_type', 'identifier']);
            $table->index(['person_id', 'identity_type']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('student.person_identities');
        Schema::dropIfExists('student.persons');
    }
};
