'use client';

import React, { FormEvent, useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import QRCode from 'qrcode';
import { api, ApiError, type IamSession } from '@mema/api-client';
import { useAuth } from '@mema/auth';
import { Alert, AlertDescription, AlertTitle, Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input } from '@mema/ui';
import { KeyRound, Laptop, LogOut, QrCode, RefreshCw, ShieldCheck } from 'lucide-react';

const labelClass = 'space-y-1 text-sm font-medium text-slate-700';
const messageFrom = (reason: unknown) => reason instanceof ApiError ? reason.message : 'The security operation could not be completed.';

export default function AccountSecurityPage() {
  const router = useRouter(); const { user, refreshSession } = useAuth();
  const [sessions, setSessions] = useState<IamSession[]>([]); const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [setup, setSetup] = useState<{ secret: string; provisioning_uri: string; qr: string } | null>(null);
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const loadSessions = useCallback(async () => { try { setSessions((await api.getSessions()).data); } catch (reason) { setError(messageFrom(reason)); } }, []);
  useEffect(() => { void loadSessions(); }, [loadSessions]);
  async function perform(action: () => Promise<void>, success: string) { setLoading(true); setError(null); setNotice(null); try { await action(); setNotice(success); } catch (reason) { setError(messageFrom(reason)); } finally { setLoading(false); } }
  async function startMfa() { await perform(async () => { const value = await api.setupMfa(); setSetup({ ...value, qr: await QRCode.toDataURL(value.provisioning_uri, { width: 240, margin: 1 }) }); }, 'Scan the QR code, then confirm with a six-digit code.'); }
  async function confirmMfa(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await perform(async () => { const response = await api.confirmMfa(String(form.get('code'))); setRecoveryCodes(response.recovery_codes); setSetup(null); await refreshSession(); }, 'MFA enabled. Store the recovery codes now; they will not be shown again.'); }
  async function disableMfa(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await perform(async () => { await api.disableMfa(String(form.get('password'))); await refreshSession(); }, 'MFA disabled.'); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await perform(async () => { await api.changePassword({ current_password: String(form.get('current_password')), password: String(form.get('password')), password_confirmation: String(form.get('password_confirmation')) }); router.replace('/login'); }, 'Password changed. Sign in again.'); }
  async function revokeSession(id: string) { await perform(async () => { await api.revokeSession(id); await loadSessions(); }, 'Session revoked.'); }
  async function logoutAll() { await perform(async () => { await api.logoutAll(); router.replace('/login'); }, 'Signed out everywhere.'); }

  return <div className="space-y-8"><div><h2 className="font-heading text-2xl font-bold text-slate-900">Account security</h2><p className="mt-1 text-sm text-slate-500">Control your password, authenticator, recovery codes, and signed-in devices.</p></div>
    {error && <Alert variant="destructive"><AlertTitle>Security operation failed</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{notice && <Alert variant="success"><AlertTitle>Security updated</AlertTitle><AlertDescription>{notice}</AlertDescription></Alert>}
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5" />Change password</CardTitle><CardDescription>Changing the password revokes every existing session and access token.</CardDescription></CardHeader><CardContent><form onSubmit={changePassword} className="space-y-4"><label className={labelClass}>Current password<Input name="current_password" type="password" required /></label><label className={labelClass}>New password<Input name="password" type="password" minLength={12} required /></label><label className={labelClass}>Confirm new password<Input name="password_confirmation" type="password" minLength={12} required /></label><Button type="submit" isLoading={loading}>Change password and sign out</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><QrCode className="h-5 w-5" />Authenticator MFA</CardTitle><CardDescription>RFC 6238 codes protect this account after password verification.</CardDescription></CardHeader><CardContent className="space-y-4"><Badge variant={user?.mfa_enabled ? 'success' : 'warning'}>{user?.mfa_enabled ? 'Enabled' : 'Not enrolled'}</Badge>{!user?.mfa_enabled && !setup && <Button onClick={() => void startMfa()} isLoading={loading}><ShieldCheck className="mr-2 h-4 w-4" />Set up authenticator</Button>}{setup && <div className="space-y-4"><Image src={setup.qr} alt="Authenticator enrollment QR code" width={240} height={240} unoptimized className="rounded-xl border border-slate-200" /><p className="break-all font-mono text-xs text-slate-600">Manual key: {setup.secret}</p><form onSubmit={confirmMfa} className="flex max-w-sm items-end gap-2"><label className={labelClass}>Six-digit code<Input name="code" inputMode="numeric" pattern="[0-9]{6}" required /></label><Button type="submit" isLoading={loading}>Confirm MFA</Button></form></div>}{recoveryCodes.length > 0 && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-semibold text-amber-950">Recovery codes — save once</h3><div className="mt-3 grid grid-cols-2 gap-2 font-mono text-sm">{recoveryCodes.map((code) => <code key={code}>{code}</code>)}</div></div>}{user?.mfa_enabled && <form onSubmit={disableMfa} className="space-y-3"><label className={labelClass}>Current password to disable MFA<Input name="password" type="password" required /></label><Button type="submit" variant="destructive" isLoading={loading}>Disable MFA</Button></form>}</CardContent></Card></div>
    <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="flex items-center gap-2"><Laptop className="h-5 w-5" />Signed-in devices</CardTitle><CardDescription>Idle and absolute expiry are enforced on every protected request.</CardDescription></div><Button variant="outline" onClick={() => void loadSessions()}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button></div></CardHeader><CardContent className="space-y-3">{sessions.map((session) => <div key={session.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-semibold">{session.device_name}</div><div className="text-xs text-slate-500">{session.ip_address} · Last active {new Date(session.last_activity_at).toLocaleString()}</div><div className="mt-1"><Badge variant={session.revoked_at ? 'warning' : session.mfa_verified ? 'success' : 'outline'}>{session.revoked_at ? 'Revoked' : session.mfa_verified ? 'MFA verified' : 'Active'}</Badge></div></div>{!session.revoked_at && <Button variant="outline" onClick={() => void revokeSession(session.id)} isLoading={loading}>Revoke session</Button>}</div>)}{sessions.length === 0 && <p className="text-sm text-slate-500">No tracked sessions found.</p>}<div className="border-t border-slate-200 pt-4"><Button variant="destructive" onClick={() => void logoutAll()} isLoading={loading}><LogOut className="mr-2 h-4 w-4" />Sign out everywhere</Button></div></CardContent></Card>
  </div>;
}
